name: Rebuild and push all images

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Install requirements
      run: |
        sudo apt update
        sudo apt install software-properties-common uidmap -y
        sudo add-apt-repository ppa:projectatomic/ppa -y
        sudo apt update
        sudo apt install -y podman buildah python3-pip python3-setuptools
        sudo pip3 install ansible

    - name: Build images
      run: sudo ansible-playbook -i ./inventory/hosts ./images.yaml -e "buildah_password=${{ secrets.push_token }}" -e "buildah_login=pavel_veber" -t all -vvvv
