name: Rebuild all images 

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        images: [debug, ide]

    steps:

    - uses: actions/checkout@master

    - name: Build the Docker image
      run: |
        sudo apt update
        sudo apt install software-properties-common uidmap -y
        sudo add-apt-repository ppa:projectatomic/ppa -y
        sudo apt update
        sudo apt install -y podman buildah
    - name: podman run
      run: |
        sudo -i
        ctr1=$(buildah from docker.io/library/fedora)
        buildah run "$ctr1" -- dnf update -y
        buildah commit "$ctr1" testimages-9282
        buildah images

        
        #run: cd ${{ matrix.images }} && docker build -t docker.pkg.github.com/pavel-veber/images/${{ matrix.images }}:latest .
