name: Rebuild all images 

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        images: [debug, ide]

    steps:

    - uses: actions/checkout@master

    - name: Build the Docker image
      run: |
        sudo apt update
        sudo apt install software-properties-common uidmap -y
        sudo add-apt-repository ppa:projectatomic/ppa -y
        sudo apt update
        sudo apt install -y podman
    - name: podman run
      run: |
        sudo podman run --rm docker.io/centos:8 cat /etc/centos-release
        
        #run: cd ${{ matrix.images }} && docker build -t docker.pkg.github.com/pavel-veber/images/${{ matrix.images }}:latest .
