name: Rebuild all images 

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
      strategy:
        matrix:
          images: [debug, ide]

    steps:

    - uses: actions/checkout@master

    - name: Install buildah
      run: |
        sudo apt update
        sudo apt install software-properties-common uidmap -y
        sudo add-apt-repository ppa:projectatomic/ppa -y
        sudo apt update
        sudo apt install -y podman buildah

    - name: Build image ${{ matrix.images }}
      run: cd ${{ matrix.images }} && ./build.py
