name: Rebuild all images 

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Install buildah
      run: |
        sudo apt update
        sudo apt install software-properties-common uidmap -y
        sudo add-apt-repository ppa:projectatomic/ppa -y
        sudo apt update
        sudo apt install -y podman buildah python3-pip python3-setuptools
        sudo pip3 install ansible

    - name: Build images
      run: sudo ansible-playbook -i ./inventory/hosts ./build.yaml -vv
